version: '3.8'

services:
  # Base de datos vectorial Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: copiloto-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - copiloto-network
    restart: unless-stopped

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: copiloto-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - VECTOR_SIZE=3072
      - MAX_PDFS=5
    volumes:
      - ./backend:/app
      - temp_pdfs:/app/temp
    depends_on:
      - qdrant
    networks:
      - copiloto-network
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: copiloto-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - copiloto-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  qdrant_storage:
    driver: local
  temp_pdfs:
    driver: local

networks:
  copiloto-network:
    driver: bridge
